### ISSUE TITLE
DeepSeek-V2-Chat-0628-GGUF  can not load.

### ISSUE THREAD

**Issue by rankaiyx** [RodriMora/video2wav#1]
https://huggingface.co/bullerwins/DeepSeek-V2-Chat-0628-GGUF

Hello, thank you for your quantitative conversion. However, it seems that it cannot be loaded on the latest version of llama.
The following is the output information of llama:

➜  llama.cpp git:(master) ./llama-cli -m ../gguf/DeepSeek-V2-Chat-0628-Q4_K_S-00001-of-00003.gguf -p "You are a helpful assistant"
Log start
main: build = 3416 (a15ef8f8)
main: built with cc (Debian 12.2.0-14) 12.2.0 for x86_64-linux-gnu
main: seed  = 1721355160
llama_model_loader: additional 2 GGUFs metadata loaded.
llama_model_loader: loaded meta data with 50 key-value pairs and 959 tensors from ../gguf/DeepSeek-V2-Chat-0628-Q4_K_S-00001-of-00003.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = deepseek2
llama_model_loader: - kv   1:                               general.type str              = model
llama_model_loader: - kv   2:                               general.name str              = DeepSeek V2 Chat 0628
llama_model_loader: - kv   3:                            general.version str              = 0628
llama_model_loader: - kv   4:                           general.finetune str              = Chat
llama_model_loader: - kv   5:                           general.basename str              = DeepSeek-V2
llama_model_loader: - kv   6:                         general.size_label str              = 160x14B
llama_model_loader: - kv   7:                            general.license str              = other
llama_model_loader: - kv   8:                       general.license.name str              = deepseek
llama_model_loader: - kv   9:                       general.license.link str              = https://github.com/deepseek-ai/DeepSe...
llama_model_loader: - kv  10:                      deepseek2.block_count u32              = 60
llama_model_loader: - kv  11:                   deepseek2.context_length u32              = 163840
llama_model_loader: - kv  12:                 deepseek2.embedding_length u32              = 5120
llama_model_loader: - kv  13:              deepseek2.feed_forward_length u32              = 12288
llama_model_loader: - kv  14:             deepseek2.attention.head_count u32              = 128
llama_model_loader: - kv  15:          deepseek2.attention.head_count_kv u32              = 128
llama_model_loader: - kv  16:                   deepseek2.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  17: deepseek2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv  18:                deepseek2.expert_used_count u32              = 6
llama_model_loader: - kv  19:                          general.file_type u32              = 14
llama_model_loader: - kv  20:        deepseek2.leading_dense_block_count u32              = 1
llama_model_loader: - kv  21:                       deepseek2.vocab_size u32              = 102400
llama_model_loader: - kv  22:            deepseek2.attention.q_lora_rank u32              = 1536
llama_model_loader: - kv  23:           deepseek2.attention.kv_lora_rank u32              = 512
llama_model_loader: - kv  24:             deepseek2.attention.key_length u32              = 192
llama_model_loader: - kv  25:           deepseek2.attention.value_length u32              = 128
llama_model_loader: - kv  26:       deepseek2.expert_feed_forward_length u32              = 1536
llama_model_loader: - kv  27:                     deepseek2.expert_count u32              = 160
llama_model_loader: - kv  28:              deepseek2.expert_shared_count u32              = 2
llama_model_loader: - kv  29:             deepseek2.expert_weights_scale f32              = 16.000000
llama_model_loader: - kv  30:             deepseek2.rope.dimension_count u32              = 64
llama_model_loader: - kv  31:                deepseek2.rope.scaling.type str              = yarn
llama_model_loader: - kv  32:              deepseek2.rope.scaling.factor f32              = 40.000000
llama_model_loader: - kv  33: deepseek2.rope.scaling.original_context_length u32              = 4096
llama_model_loader: - kv  34: deepseek2.rope.scaling.yarn_log_multiplier f32              = 0.100000
llama_model_loader: - kv  35:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  36:                         tokenizer.ggml.pre str              = deepseek-llm
llama_model_loader: - kv  37:                      tokenizer.ggml.tokens arr[str,102400]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  38:                  tokenizer.ggml.token_type arr[i32,102400]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  39:                      tokenizer.ggml.merges arr[str,99757]   = ["Ġ Ġ", "Ġ t", "Ġ a", "i n", "h e...
llama_model_loader: - kv  40:                tokenizer.ggml.bos_token_id u32              = 100000
llama_model_loader: - kv  41:                tokenizer.ggml.eos_token_id u32              = 100001
llama_model_loader: - kv  42:            tokenizer.ggml.padding_token_id u32              = 100001
llama_model_loader: - kv  43:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  44:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  45:                    tokenizer.chat_template str              = {% if not add_generation_prompt is de...
llama_model_loader: - kv  46:               general.quantization_version u32              = 2
llama_model_loader: - kv  47:                                   split.no u16              = 0
llama_model_loader: - kv  48:                                split.count u16              = 3
llama_model_loader: - kv  49:                        split.tensors.count i32              = 959
llama_model_loader: - type  f32:  300 tensors
llama_model_loader: - type q4_K:  645 tensors
llama_model_loader: - type q5_K:   13 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens cache size = 18
llm_load_vocab: token to piece cache size = 0.6411 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = deepseek2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 102400
llm_load_print_meta: n_merges         = 99757
llm_load_print_meta: vocab_only       = 0
llm_load_print_meta: n_ctx_train      = 163840
llm_load_print_meta: n_embd           = 5120
llm_load_print_meta: n_layer          = 60
llm_load_print_meta: n_head           = 128
llm_load_print_meta: n_head_kv        = 128
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_swa            = 0
llm_load_print_meta: n_embd_head_k    = 192
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 24576
llm_load_print_meta: n_embd_v_gqa     = 16384
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 12288
llm_load_print_meta: n_expert         = 160
llm_load_print_meta: n_expert_used    = 6
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = yarn
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 0.025
llm_load_print_meta: n_ctx_orig_yarn  = 4096
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 236B
llm_load_print_meta: model ftype      = Q4_K - Small
llm_load_print_meta: model params     = 235.74 B
llm_load_print_meta: model size       = 124.68 GiB (4.54 BPW)
llm_load_print_meta: general.name     = DeepSeek V2 Chat 0628
llm_load_print_meta: BOS token        = 100000 '<｜begin▁of▁sentence｜>'
llm_load_print_meta: EOS token        = 100001 '<｜end▁of▁sentence｜>'
llm_load_print_meta: PAD token        = 100001 '<｜end▁of▁sentence｜>'
llm_load_print_meta: LF token         = 126 'Ä'
llm_load_print_meta: max token length = 256
llm_load_print_meta: n_layer_dense_lead   = 1
llm_load_print_meta: n_lora_q             = 1536
llm_load_print_meta: n_lora_kv            = 512
llm_load_print_meta: n_ff_exp             = 1536
llm_load_print_meta: n_expert_shared      = 2
llm_load_print_meta: expert_weights_scale = 16.0
llm_load_print_meta: rope_yarn_log_mul    = 0.1000
llm_load_tensors: ggml ctx size =    0.40 MiB
llm_load_tensors:        CPU buffer size = 42437.21 MiB
llm_load_tensors:        CPU buffer size = 42670.70 MiB
llm_load_tensors:        CPU buffer size = 42562.19 MiB
....................................................................................................
llama_new_context_with_model: n_ctx      = 163840
llama_new_context_with_model: n_batch    = 2048
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 0.025
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 805306368032
llama_kv_cache_init: failed to allocate buffer for kv cache
llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
llama_init_from_gpt_params: error: failed to create context with model '../gguf/DeepSeek-V2-Chat-0628-Q4_K_S-00001-of-00003.gguf'
main: error: unable to load model

**Comment by RodriMora** [comment]
Hi! The kv cache is really big, so even if you had enough VRAM/RAM and looks like it should fit, it actually requires way more. So you might need way more RAM or VRAM if want to offload some layers.

You don't have a HF account to post it there?

**Comment by rankaiyx** [comment]
Yes, I'm sorry, I don't have an HF account. 
I tested it on a computer with 256G RAM.

**Comment by rankaiyx** [comment]
Did you run successfully?

**Comment by rankaiyx** [comment]
The key point may be here:
ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 805306368032

I found that 805306368032 is exactly equal to 750GiB. Does this model really need such a huge buffer?
805,306,368,032 Byte=750.0000 GiB

**Comment by RodriMora** [comment]
> Did you run successfully?

yeah, I managed to run Q2. Which quant are you running? can you try with Q2 and work you way up?

**Comment by rankaiyx** [comment]
Q4_K_S

**Comment by rankaiyx** [comment]
OK, I will test Q2

**Comment by RodriMora** [comment]
Please try to limit the context with "-c 4000". It's a really big model with big KV

**Comment by rankaiyx** [comment]
limit the context with "-c 4000"
it's successfully!
The default context is crazy 163840, no wonder need such a big KV
